cd /Volumes/FILE/VS\ Projects/DataEditor.Ruby/DataEditor.Titan/Ruby
cd xp
touch "Actor - xp.rb"
touch "Class - xp.rb"
touch "Skill - xp.rb"
touch "Item - xp.rb"
touch "Weapon - xp.rb"
touch "Armor - xp.rb"
touch "Enemy - xp.rb"
touch "Troop - xp.rb"
touch "State - xp.rb"
touch "Animation - xp.rb"
touch "CommonEvent - xp.rb"
touch "System - xp.rb"
touch "Tileset - xp.rb"
cd ..
cd vx
touch "Actor - vx.rb"
touch "Class - vx.rb"
touch "Skill - vx.rb"
touch "Item - vx.rb"
touch "Weapon - vx.rb"
touch "Armor - vx.rb"
touch "Enemy - vx.rb"
touch "Troop - vx.rb"
touch "State - vx.rb"
touch "Animation - vx.rb"
touch "CommonEvent - vx.rb"
touch "System - vx.rb"
touch "Term - vx.rb"
cd ..
cd va
touch "Actor - va.rb"
touch "Class - va.rb"
touch "Skill - va.rb"
touch "Item - va.rb"
touch "Weapon - va.rb"
touch "Armor - va.rb"
touch "Enemy - va.rb"
touch "Troop - va.rb"
touch "State - va.rb"
touch "Animation - va.rb"
touch "CommonEvent - va.rb"
touch "System - va.rb"
touch "Term - va.rb"
touch "Tileset - va.rb"
